### ISSUE TITLE
Add support for complex data types

### ISSUE THREAD

**Issue by tsahiduek** [kro-run/kro#144]
### Feature Description

**Problem Statement**:
For complex objects, such as ACK DyanmoDB Table definition, there's a need to define a complex data-types that will be used as an input for the ResourceGroup.
As an example, ACK DynamoDB Table gets as an input, a list of the following struct:
```
 attributeDefinitions:
    - attributeName: id
      attributeType: S
    - attributeName: name
      attributeType: S
```

Currently there's no way to define the following:
```
tableElement: map[string][string]
attributeDefinition: []tableElement
```

**Proposed Solution**:
support complex data types to be able to pass those as an input to the ResourceGroup spec values.

**Alternatives Considered**:
none

**Additional Context**:
none

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue
* If you are interested in working on this feature, please leave a comment

**Comment by franckyvrac** [comment]
I've got the same problem to define list of protocols and ports in an networkpolicy :


```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np
spec:
  egress:
  - ports:
    - port: 21
      protocol: TCP
    - port: 25
      protocol: TCP
    - port: 80
      protocol: TCP
    - port: 443
      protocol: TCP
```

**Comment by gfrey** [comment]
I like the idea, but wondered about the simple schema specification would be more natural and flexible. The following would be the simplest extension to the already existing configuration:
``` yaml
spec:
  schema:
    apiVersion: v1
    kind: MyExample
    spec:
      listOfStructuredTypes:
      - value1: string | required=true
        value2: integer | default=42
```

Upon applying this to K8s I get the following error condition:
``` yaml    
  - lastTransitionTime: "2025-04-07T07:54:04Z"
    message: Directed Acyclic Graph is synced
    reason: 'failed to build resourcegraphdefinition ''my-example'': failed to build
      OpenAPI schema for instance: failed to build OpenAPI schema for instance: unknown
      type in schema: key: listOfStructuredTypes, value: [map[value1:string | required=true
      value2:integer | default=42]]'
```

So, I guess, the thing missing is this way of defining arrays. If that would be allowed, the question remains how to define additional properties to the `listOfStructuredTypes`, like number of required elements.

**Comment by gfrey** [comment]
After discussion with @a-hilaly he suggested to use the following pattern:
``` yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: service-entry-dns
spec:
  schema:
    apiVersion: v1alpha1
    kind: ServiceEntryDNS
    spec:
      ports: "[]port | required=true"
    customTypes:
      port:
         name: string
         protocol: string
         number: integer | required
```
This also solves the problem of markers (that I called "additional properties" in yesterdays comment).

**Comment by fsommar** [comment]
That'd solve my use case too.

I'm curious if it could be extended to support primitive newtypes, like:

```yaml
schema:
  spec:
    genre: genre
customTypes:
  genre: string | required enum="pop,rock,soul"
```

Although, that brings with it the perhaps undesirable property of hiding markers from where they're declared. It can be "solved" with using yaml anchors to redefine a type with markers in multiple places without duplicated work, so not a requirement, just curious to hear thoughts.

**Comment by gfrey** [comment]
@fsommar defining primitive type aliases with markers works with the implementation from PR #496. Thanks for asking and making me double check this "feature". It was indeed broken for the `required` marker (see dedicated comment).

**Comment by btwseeu78** [comment]
I have already added this here https://github.com/kro-run/kro/issues/17 but this topic maybe more suitable here,
How about object bases substitution, like how helm template works, like toYaml function in helm.

we are substituting {{ $schema.spec.containers } let containers be an object rather than  value type.
so we can do like this.

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: my-application
spec:
  # kro uses this simple schema to create your CRD schema and apply it
  # The schema defines what users can provide when they instantiate the RGD (create an instance).
  schema:
    apiVersion: v1alpha1
    kind: Application
    spec:
      containers:
        - name: conatiner1
        - name: container2
```

```yaml
containers:
{{ $.schema.spec.containers }}

```
