### ISSUE TITLE
Make Group name configurable within ResourceGroup

### ISSUE THREAD

**Issue by amirahav** [kro-run/kro#164]
### Feature Description

**Problem Statement**:

The `Group` name of the CRD created by a `ResourceGroup` is currently hardcoded. It would be beneficial to be able to define the group name to assist in differentiating kro specific CRDs and user/customer defined CRDs.
 
**Proposed Solution**:

Add a `group` attribute within `spec.schema` which should default to `kro.run`, similar to this:

```
apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: sqs-queue
spec:
  schema:
    apiVersion: v1alpha1
    kind: Queue
    group: somegroup.xyz.com
    spec:
      ...
```

**Alternatives Considered**:

**Additional Context**:

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue
* If you are interested in working on this feature, please leave a comment
