### ISSUE TITLE
Disallow creation of ResourceGroups if value of immutable field is invalid

### ISSUE THREAD

**Issue by amirahav** [kro-run/kro#165]
### Description

**Observed Behavior**:
kro currently allows a ResourceGroup with an invalid value of an immutable field to be created.
This then requires the deletion and recreation of the ResourceGroup.

**Expected Behavior**:
The kro controller returns an error and doesn't create the ResourceGroup.

**Reproduction Steps** (Please include `ResourceGroup` and `Instances` files):

```
apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: sqs-queue
spec:
  schema:
    apiVersion: v1alpha1
    kind: sqs-queue
    spec:
      ...
```

**Versions**:
- kro version:
- Kubernetes Version (`kubectl version`):

**Involved Controllers**:
- Controller URLs and Versions (if applicable):
- kro v0.1.0

**Error Logs** (if applicable)**:
```
Paste any relevant logs here
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
