### ISSUE TITLE
Failed to extract CEL expressions from schema for resource `program`

### ISSUE THREAD

**Issue by dirien** [kro-run/kro#255]
### Description

**Observed Behavior**:

I am using following `ResourceGraphDefinition`

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: my-pko-app
spec:
  schema:
    apiVersion: v1alpha1
    kind: MyApplication
    spec:
      name: string
      stack: string
      gitRepo: string
      region: string | default="nyc1"
      instanceCount: integer | default=1
      instanceSizeSlug: string | default="apps-s-1vcpu-1gb"
  resources:
  - id: program
    template:
      apiVersion: pulumi.com/v1
      kind: Program
      metadata:
        name: ${schema.spec.name}
      program:
        resources:
          app:
            type: digitalocean:App
            properties:
              spec:
                name: app-${schema.spec.name}-${schema.spec.region}
                region: ${schema.spec.region}
                services:
                - name: app-service-${schema.spec.name}-${schema.spec.region}
                  instanceCount: ${schema.spec.instanceCount}
                  instanceSizeSlug: ${schema.spec.instanceSizeSlug}
                  git:
                    repoCloneUrl: ${schema.spec.gitRepo}
                    branch: "main"
  - id: stack
    template:
      apiVersion: pulumi.com/v1
      kind: Stack
      metadata:
        name: ${schema.spec.name}
      spec:
        stack: ${schema.spec.stack}
        envRefs:
          DIGITALOCEAN_TOKEN:
            type: Env
            env:
              name: DIGITALOCEAN_TOKEN
        programRef:
          name: ${schema.spec.name}
        destroyOnFinalize: true
````

When I apply this `rgd`, I get following error message:

```yaml
message: Directed Acyclic Graph is synced                                                                                                     
reason: 'failed to build resource ''program'': failed to extract CEL expressions from schema for resource program: schema at path program.resources.app.properties.spec has no valid type, OneOf, AnyOf, or AdditionalProperties'     
```                                                                                  

**Expected Behavior**:

Apply the `rgd` without a problem

**Reproduction Steps** (Please include `ResourceGraphDefinition` and `Instances` files):

**Versions**:
- kro version: 0.2
- Kubernetes Version (`kubectl version`): Server Version: v1.32.0

**Involved Controllers**:
- Controller URLs and Versions (if applicable):

**Error Logs** (if applicable)**:

```json
2025-01-31T10:37:45.906Z    DEBUG    controller.resourceGraphDefinition    processing reconciliation error    {"resourcegraphdefinition": {"name":"my-pko
-app"}, "error": "failed to build resource 'program': failed to extract CEL expressions from schema for resource program: schema at path program.resource
s.app.properties.spec has no valid type, OneOf, AnyOf, or AdditionalProperties"}
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rushmash91** [comment]
Thank you for opening this issue and providing the details! 

From the error message, it looks like the parser is running into a problem with the schema at `program.resources.app.properties.spec`, and specifically that it can’t determine a valid type. It may be an issue with how the resource type is declared or interpreted in the CRD.

Would you be able to share the CRD you’re using for this setup? That might help us reproduce the issue and get a better sense of where the parsing is failing.

**Comment by a-hilaly** [comment]
Thank you for reporting this! I was able reproduced the issue - the [Pulumi Program CRD](https://github.com/pulumi/pulumi-kubernetes-operator/blob/master/operator/config/crd/bases/pulumi.com_programs.yaml) has a special schema pattern where it combines `additionalProperties` (for allowing arbitrary resource names) with `x-kubernetes-preserve-unknown-fields` in a nested structure, essentially forming a `map[string]struct{properties any}` pattern:
```yaml
resources:
  additionalProperties:  # map[string]->struct{}
    properties:
      properties:        # struct{properties any}
        x-kubernetes-preserve-unknown-fields: true
```

The structured resource parser wasn't properly handling this combination of features - I opened #260 to improve the parser package
