### ISSUE TITLE
Some created resources keep as "not resolved: state=WaitingOnDependencies"

### ISSUE THREAD

**Issue by allamand** [kro-run/kro#271]
### Description

**Observed Behavior**:
i'm created a resource:

```
    - id: accessEntryAdmin
      template:
        apiVersion: eks.services.k8s.aws/v1alpha1
        kind: AccessEntry
        metadata:
          namespace: ${schema.spec.name}
          name: ${schema.spec.name}-access-entry-admin
        spec:
          clusterName: ${schema.spec.name}
          accessPolicies:
            - accessScope:
                type: "cluster"
              policyARN: "arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy"
          principalARN: "arn:aws:iam::${schema.spec.accountId}:role/${schema.spec.adminRoleName}"
          type: STANDARD
```

I can see that the resource is correctly created and reconciled:

```
k get accessentries.eks.services.k8s.aws -n workload-cluster3 workload-cluster3-access-entry-admin -o yaml 

...
status:
  ackResourceMetadata:
    arn: arn:aws:eks:us-west-2:012345678910:access-entry/workload-cluster3/role/012345678910/Admin/6eca67fc-ab9d-e6ae-80d0-2c2e281b5b8b
    ownerAccountID: "012345678910"
    region: us-west-2
  conditions:
  - lastTransitionTime: "2025-02-04T08:00:13Z"
    message: Resource synced successfully
    reason: ""
    status: "True"
    type: ACK.ResourceSynced
  createdAt: "2025-02-04T08:00:12Z"
  modifiedAt: "2025-02-04T08:00:12Z"
```

but kro keep looping with this logs message, and is not creating next resources in my stack

```
kro-6d5b8f8b8f-4kcr2 kro 2025-02-04T08:26:21.856Z       LEVEL(-2)       controller.eksclusters  Using resource-specified namespace      {"namespace": "workload-cluster3", "name": "workload-cluster3", "resourceID": "accessEntry", "namespace": "workload-cluster3"}
kro-6d5b8f8b8f-4kcr2 kro 2025-02-04T08:26:21.860Z       DEBUG   controller.eksclusters  Processing resource update      {"namespace": "workload-cluster3", "name": "workload-cluster3", "resourceID": "accessEntry"}
kro-6d5b8f8b8f-4kcr2 kro 2025-02-04T08:26:21.860Z       DEBUG   controller.eksclusters  No deltas found for resource    {"namespace": "workload-cluster3", "name": "workload-cluster3", "resourceID": "accessEntry"}
kro-6d5b8f8b8f-4kcr2 kro 2025-02-04T08:26:21.870Z       DEBUG   dynamic-controller      Requeue needed after delay      {"item": {"NamespacedKey":"workload-cluster3/workload-cluster3","GVR":{"Group":"kro.run","Version":"v1alpha1","Resource":"eksclusters"}}, "error": "resource accessEntryAdmin not resolved: state=WaitingOnDependencies", "delay": "3s"}
```

**Expected Behavior**:

I would expect that kro see that the resource has been correctly created

**Versions**:
- kro version: 0.2.0
- Kubernetes Version (`kubectl version`):v1.30.8-eks-2d5f260

**Involved Controllers**:
- Controller URLs and Versions (if applicable): ACK EKS

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
*
