### ISSUE TITLE
When relying on default values, we need to at list provided 1 value for yaml sub-path

### ISSUE THREAD

**Issue by allamand** [kro-run/kro#322]
### Description

**Observed Behavior**:

Let's say I have this ressource:

```
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: eksclusterwithvpc.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: EksclusterWithVpc
    spec:
      name: string
      tenant: string | default="tenant1"
      environment: string | default="staging"
      region: string
      k8sVersion: string
      adminRoleName: string | default="Admin"
      fleetSecretManagerSecretNameSuffix: string
      cidr:
        vpcCidr: string | default="10.0.0.0/16"
        publicSubnet1Cidr: string | default="10.0.1.0/24"
        publicSubnet2Cidr: string | default="10.0.2.0/24"
        privateSubnet1Cidr: string | default="10.0.11.0/24"
        privateSubnet2Cidr: string | default="10.0.12.0/24"
      gitops:
        addonsRepoBasePath: string | default="gitops/addons/"
        addonsRepoPath: string | default="bootstrap"
        addonsRepoRevision: string | default="HEAD"
      addons:
        external_dns_namespace: string | default="external-dns"
        external_dns_service_account: string | default="external-dns-sa"
        external_dns_policy: string | default="sync"
```

I have defined some defaults for all cidr, gitops and addons sections.

But If I instantiate an object with:

```
apiVersion: kro.run/v1alpha1
kind: EksclusterWithVpc
metadata:
  name: workload-cluster1
spec:
    name: workload-cluster1
    region: us-west-2
    k8sVersion: '1.30'
    fleetSecretManagerSecretNameSuffix: argocd-secret    
  ```

then I have this error:

```
kro-b64f599f8-mk6dw kro 2025-02-19T18:09:47.225Z        ERROR   dynamic-controller      Error syncing item, requeuing with rate limit   {"item": {"NamespacedKey":"default/workload-cluster1","GVR":{"Group":"kro.run","Version":"v1alpha1","Resource":"eksclusterwithvpcs"}}, "error": "failed to create runtime resource graph definition: failed to evaluate static variables: failed evaluating expression schema.spec.cidr.publicSubnet1Cidr: no such key: cidr"}
```

For that I need to include at list 1 elements of the **cidr**, **gitops** and **addons** sections:

```
apiVersion: kro.run/v1alpha1
kind: EksclusterWithVpc
metadata:
  name: workload-cluster1
spec:
    name: workload-cluster1
    region: us-west-2
    k8sVersion: '1.30'
    fleetSecretManagerSecretNameSuffix: argocd-secret    
    cidr:
      vpcCidr: "10.0.0.0/16"
    gitops:
      addonsRepoRevision: "seb"
    addons:
      external_dns_namespace: 'external-dns'
```

**Expected Behavior**:

I would expect it to choose default values in all cases.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by michaelhtm** [comment]
Hey @allamand, we have noticed the issue too, and the way we got around it is by initializing parent fields as empty, eg:
```yaml
apiVersion: kro.run/v1alpha1
kind: EksclusterWithVpc
metadata:
  name: workload-cluster1
spec:
    name: workload-cluster1
    region: us-west-2
    k8sVersion: '1.30'
    fleetSecretManagerSecretNameSuffix: argocd-secret    
    cidr: {}
    gitops:
      addonsRepoRevision: "seb"
    addons:
      external_dns_namespace: 'external-dns'
```

I do think it would be nicer if the controller was able to handle this..
