### ISSUE TITLE
failed to synchronize reconciling resource deployment:

### ISSUE THREAD

**Issue by rootxrishabh** [kro-run/kro#336]
### Description

**Observed Behavior**:
When creating an application from a RGD, if the RGD uses a variable from the status of the application object then application state returns FAILED. This happens due to the status parameter unavailable till the time the application object gets ready. It then eventually transitions to ACTIVE state.
**Expected Behavior**:
Ideally the status should show NotReady or Waiting and wait for the application resource objects to get into ready state.
**Reproduction Steps** (Please include `ResourceGraphDefinition` and `Instances` files):
Following the [Deploy Your First Resource Graph](https://kro.run/docs/getting-started/deploy-a-resource-graph-definition#create-your-application-resourcegraphdefinition) guide.

**Versions**:
- kro version: 0.2.1
- Kubernetes Version (`kubectl version`): v1.31.5

**Error Logs** (if applicable)**:
```
rootxrishabh@rootxrishabh ~> kubectl apply -f app.yml 
application.kro.run/my-application-instance created
rootxrishabh@rootxrishabh ~> kubectl get applications
NAME                      STATE   SYNCED   AGE
my-application-instance   ERROR   False    4s

rootxrishabh@rootxrishabh ~> k describe application my-application-instance
Name:         my-application-instance
Namespace:    kro
Labels:       kro.run/controller-pod-id=kro-pod
              kro.run/kro-version=0.2.1
              kro.run/owned=true
              kro.run/resource-graph-definition-id=8518c669-125f-422c-9a33-7415a67f385f
              kro.run/resource-graph-definition-name=my-application
              kro.run/resource-graph-definition-namespace=
Annotations:  <none>
API Version:  kro.run/v1alpha1
Kind:         Application
Metadata:
  Creation Timestamp:  2025-02-28T19:35:27Z
  Finalizers:
    kro.run/finalizer
  Generation:        1
  Resource Version:  61359
  UID:               2c35ea07-1198-4f8a-8ef7-104c302eccad
Spec:
  Image:  nginx
  Ingress:
    Enabled:  true
  Name:       my-awesome-app
Status:
  Conditions:
    Last Transition Time:  2025-02-28T19:35:43Z
    Message:               failed to synchronize reconciling resource deployment: failed to evaluate dynamic variables: incomplete data: failed evaluating expression deployment.status.availableReplicas: no such key: availableReplicas
    Observed Generation:   1
    Reason:                ReconciliationFailed
    Status:                False
    Type:                  InstanceSynced
  State:                   ERROR
Events:                    <none>

```

Then auto transitions to ACTIVE state - 
```
rootxrishabh@rootxrishabh ~> k get application
NAME                      STATE    SYNCED   AGE
my-application-instance   ACTIVE   True     59s
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rushmash91** [comment]
Hi @rootxrishabh, Mind sharing both the RGD and instance manifests you're using? Would really help reproduce this and take a better look

**Comment by rootxrishabh** [comment]
Hi @rushmash91, here's the RGD -
```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: my-application
spec:
  # kro uses this simple schema to create your CRD schema and apply it
  # The schema defines what users can provide when they instantiate the RGD (create an instance).
  schema:
    apiVersion: v1alpha1
    kind: Application
    spec:
      # Spec fields that users can provide.
      name: string
      image: string | default="nginx"
      ingress:
        enabled: boolean | default=false
    status:
      # Fields the controller will inject into instances status.
      deploymentConditions: ${deployment.status.conditions}
      availableReplicas: ${deployment.status.availableReplicas}

  # Define the resources this API will manage.
  resources:
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.spec.name} # Use the name provided by user
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: ${schema.spec.name}
          template:
            metadata:
              labels:
                app: ${schema.spec.name}
            spec:
              containers:
                - name: ${schema.spec.name}
                  image: ${schema.spec.image} # Use the image provided by user
                  ports:
                    - containerPort: 80

    - id: service
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: ${schema.spec.name}-service
        spec:
          selector: ${deployment.spec.selector.matchLabels} # Use the deployment selector
          ports:
            - protocol: TCP
              port: 80
              targetPort: 80

    - id: ingress
      includeWhen:
        - ${schema.spec.ingress.enabled} # Only include if the user wants to create an Ingress
      template:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: ${schema.spec.name}-ingress
          annotations:
            kubernetes.io/ingress.class: alb
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/healthcheck-path: /health
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
            alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60
        spec:
          rules:
            - http:
                paths:
                  - path: "/"
                    pathType: Prefix
                    backend:
                      service:
                        name: ${service.metadata.name} # Use the service name
                        port:
                          number: 80
```


Here's the instance - 
```yaml
apiVersion: kro.run/v1alpha1
kind: Application
metadata:
  name: my-application-instance
spec:
  name: my-awesome-app
  ingress:
    enabled: true
```

**Comment by yashisrani** [comment]
@rootxrishabh I guess you took reference from this YouTube tutorial.

https://www.youtube.com/watch?v=oCGHDbARTg0

**Comment by Joseph-Irving** [comment]
I've found this to be particularly noticeable when you are relying on something that takes a long time to provision.
For example if I'm creating a elasticache redis cluster it takes around 10-20 minutes. I want to pass the endpoint of the cluster to my deployment, but during the time it takes for the cluster to provision the `status.configurationEndpoint.address` is null so I get constant errors from Kro. 
```
failed to synchronize reconciling resource redis: failed to evaluate dynamic variables: incomplete data: failed evaluating expression redis.status.configurationEndpoint.address: no such key: configurationEndpoint
```
Kro has gone has put this resource onto a long backoff at this point so even when the cluster does finish provisioning it takes a while for Kro to realise that the field now exists and that it can now create the deployment.

```yaml
  resources:
    - id: redis
      template:
        apiVersion: elasticache.services.k8s.aws/v1alpha1
        kind: ReplicationGroup
        metadata:
          name: ${schema.spec.name}
        spec:
          atRestEncryptionEnabled: true
          automaticFailoverEnabled: true
          replicationGroupID: ${schema.spec.name}
          description: "a new cluster is here"
          cacheNodeType: "cache.t3.micro"
          cacheSubnetGroupName: ${redisSubnetGroup.spec.cacheSubnetGroupName}
          cacheParameterGroupName: default.redis7.cluster.on
          engine: "redis"
          engineVersion: "7.1"
          multiAZEnabled: true
          numNodeGroups: 1
          replicasPerNodeGroup: 2

   - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.spec.name} 
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: ${schema.spec.name}
          template:
            metadata:
              labels:
                app: ${schema.spec.name}
            spec:
              containers:
                - name: ${schema.spec.name}
                  image: ${schema.spec.image} 
                  ports:
                    - containerPort: 80
                  env:
                  - name: "redis_url"
                    value: ${redis.status.configurationEndpoint.address}

```
