### ISSUE TITLE
Add support for custom functions

### ISSUE THREAD

**Issue by fsommar** [kro-run/kro#361]
### Feature Description

**Problem Statement**:
I have repeat transformations that I want to do in various places, such as transforming a Google Cloud Project (GCP) region into a GCP zone (effectively a lookup table), or concatenating strings to create identifiers.

**Proposed Solution**:
Introduce a new spec-level field called `functions` (I have no preferences on naming convention) that looks something like the following:

```yaml
functions:
- id: greeting
  inputs:
  - string
  - string
  template: ${_0 + " " + _1 + "!"}
```

It can then be used as such

```yaml
resources:
- id: configmap
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${schema.metadata.name}
    data:
      greeting: ${greeting("Hello", "world")}
```

Which results in

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: foobar
data:
  greeting: Hello world!
```

**Alternatives Considered**:
Support hardcoded lookup tables as a map from string to string. This only solves a small subset of use cases.

**Additional Context**:
I haven't looked too much into the possibilities of CEL, but it supports maps and objects, so it could theoretically be possible to have a function return an object and have that reified as a yaml object. Is it feasible in the context of Kro? Supporting complex objects could definitely be a v2, starting with supporting primitive arguments. It may also be dependent on the approach chosen in https://github.com/kro-run/kro/issues/144.

With object support, it could be used to solve the use cases highlighted in https://github.com/kro-run/kro/issues/17 to expand input into a list in the output (such as the containers field in Deployment kinds) as opposed to expanding input into a list of resources.

Here's a PoC to prove the feasibility of dynamically registering functions
```go
package main

import (
	"fmt"
	"log"

	"github.com/google/cel-go/cel"
	"github.com/google/cel-go/common/types"
	"github.com/google/cel-go/common/types/ref"
)

type Function struct {
	id       string
	types    []string
	template string
}

func (f *Function) GetCelFunction() (cel.EnvOption, error) {
	envOpts := make([]cel.EnvOption, len(f.types))
	celTypes := make([]*cel.Type, len(f.types))
	for i, inputType := range f.types {
		celType, err := getCelType(inputType)
		if err != nil {
			return nil, err
		}

		envOpts[i] = cel.Variable(fmt.Sprintf("_%d", i), celType)
		celTypes[i] = celType
	}

	env, err := cel.NewEnv(envOpts...)
	if err != nil {
		return nil, fmt.Errorf("environment creation: %w", err)
	}

	ast, iss := env.Compile(f.template)
	if iss.Err() != nil {
		return nil, fmt.Errorf("function parse: %w", iss.Err())
	}

	prg, err := env.Program(ast)
	if err != nil {
		return nil, fmt.Errorf("program creation: %w", err)
	}

	return cel.Function(f.id,
		cel.Overload(f.id,
			celTypes,
			ast.OutputType(),
			cel.FunctionBinding(func(args ...ref.Val) ref.Val {
				vars := map[string]any{}
				for i, arg := range args {
					vars[fmt.Sprintf("_%d", i)] = arg
				}
				out, _, err := prg.Eval(vars)
				if err != nil {
					return types.WrapErr(err)
				}
				return out
			}),
		),
	), nil
}

func getCelType(typeName string) (*cel.Type, error) {
	switch typeName {
	case "string":
		return cel.StringType, nil
	case "int":
		return cel.IntType, nil
	case "double":
		return cel.DoubleType, nil
	case "bool":
		return cel.BoolType, nil
	default:
		return nil, fmt.Errorf("unsupported type: %s", typeName)
	}
}

func ExampleDynamicGlobalFunction() error {
	helloWorldFn := &Function{
		id:       "greeting",
		types:    []string{"string", "string"},
		template: `_0 + " " + _1 + "!"`,
	}

	celFunction, err := helloWorldFn.GetCelFunction()
	if err != nil {
		return fmt.Errorf("get cel function: %w", err)
	}

	env, err := cel.NewEnv(celFunction)
	if err != nil {
		return fmt.Errorf("environment creation: %w", err)
	}

	ast, iss := env.Compile(`greeting("Hello", "world")`)
	if iss.Err() != nil {
		return fmt.Errorf("parse: %w", iss.Err())
	}

	prg, err := env.Program(ast)
	if err != nil {
		return fmt.Errorf("program creation: %w", err)
	}

	out, _, err := prg.Eval(map[string]any{})
	if err != nil {
		return fmt.Errorf("evaluation: %w", err)
	}

	fmt.Println(out)
	return nil
}

func main() {
	if err := ExampleDynamicGlobalFunction(); err != nil {
		log.Fatalf("Error: %v", err)
	}
}
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue
* If you are interested in working on this feature, please leave a comment

**Comment by Jayanta111** [comment]
@fsommar 
Proposed Solution:
The idea is to introduce a new functions field at the spec level. This field would allow defining reusable functions that can then be referenced throughout the resource definitions. These functions can accept inputs and apply transformations in a template-like fashion.

Here’s how it might look:
functions:
  - id: greeting
    inputs:
      - string
      - string
    template: ${_0 + " " + _1 + "!"}

resources:
  - id: configmap
    template:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: ${schema.metadata.name}
      data:
        greeting: ${greeting("Hello", "world")}

**Comment by fsommar** [comment]
@Jayanta111 I don't follow what you're saying. It looks like your suggestion is the same as mine. Can you repeat it in another way?

**Comment by matthchr** [comment]
I wonder if there is some way to allow defining CEL functions in Go, which we dynamically include in the CEL environment in certain contexts...

The advantage being that you could write the function in something other than YAML.

**Comment by fsommar** [comment]
> I wonder if there is some way to allow defining CEL functions in Go, which we dynamically include in the CEL environment in certain contexts...
> 
> The advantage being that you could write the function in something other than YAML.

That would be really cool as an extension.

I imagine something like:

```yaml
apiVersion: fns.kro.run/v1alpha1
kind: WasmFunction
metadata:
  name: add
spec:
  image: oci://foobar-add
  function: add
```

and in the RGD
```yaml
functions:
- id: add
  functionRef:
    # group assumed to be fns.kro.run
    kind: WasmFunction
    name: add
```

And `functionRef` would be duck typed for resources that support the typecheck and apply subresources. There may be some prior art that I'm unaware of?
