### ISSUE TITLE
Support referencing metadata fields in RGD

### ISSUE THREAD

**Issue by tomasaschan** [kro-run/kro#377]
### Feature Description

**Problem Statement**:
When defining a new resource type, the CEL expressions today can only reference fields specified in the `spec.schema` section of the RGD. This is severely limiting in several ways:

* It requires the user to explicitly specify a name for their instance, even though they already have one in `.metadata.name`, if any additional logic is to be applied to naming (e.g. deriving three new resource names based on the instance), since there is no way for the CEL expressions that generate new resources to reference the metadata properties of the instance itself

* It makes it impossible to reference fields not explicitly specified in the schema or subresource definition, but which we know will be there - e.g. one cannot set `status.created: ${myresource.metadata.creationTimestamp}` to have the creation timestamp of the underlying resource be displayed in the instance status, because `creationTimestamp` is not a known field on the subresource (and we can't add it to the resource definition, as creating resources with it set is not supported).

**Proposed Solution**:
The instance `metadata` node (with underlying type `ObjectMeta` and the schema that follows from there) is exposed to the CEL expressions in the resource graph under some appropriate top-level name.

Furthermore, the resource graph entries also expose _their_ `metadata` under that name, so that `myresource.metadata` works, even if `metadata` only has e.g. `name` specified in the resource definition.

**Additional Context**:
Here's a sample RGD that uses these features, that I would like to have working but it does not:
```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: using-metadata
spec:
  schema:
    apiVersion: v1alpha1
    kind: UsingMetadata
    spec:
      data:
        foo: string
        bar: integer
    status:
      created: ${configmap.metadata.creationTimestamp} # doesn't work - but should!
  resources:
    - id: configmap
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: ${instance.metadata.name + "-cm"} # doesn't work - but should!
        data:
          foo: ${schema.spec.data.foo}
          bar: ${string(schema.spec.data.bar)}
```
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue
* If you are interested in working on this feature, please leave a comment
