### ISSUE TITLE
The status.conditions field doesn't follow Kubernetes conventions

### ISSUE THREAD

**Issue by fsommar** [kro-run/kro#415]
### Description

**Observed Behavior**:

The field `status.conditions` does not follow established Kubernetes conventions when it comes to the contents of the fields. The structure of the conditions follows the convention, though. Here's part of an example RGD status that does not look like what I'd expect:

```yaml
status:
  state: Inactive
  conditions:
  - lastTransitionTime: "2025-03-18T10:30:45Z"
    message: Directed Acyclic Graph is synced
    reason: 'failed to validate resource CEL expressions: failed to dry-run expression
      schema.spec.regions[2]: failed to evaluate expression: index out of bounds:
      2'
    status: "False"
    type: GraphVerified
  - lastTransitionTime: "2025-03-18T10:30:45Z"
    message: micro controller is ready
    reason: Faulty Graph
    status: Unknown
    type: ReconcilerReady
  - lastTransitionTime: "2025-03-18T10:30:45Z"
    message: Custom Resource Definition is synced
    reason: Faulty Graph
    status: Unknown
    type: CustomResourceDefinitionSynced
```

**Expected Behavior**:

I expect `status.conditions` to follow [Kubernetes status conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties). The above should be something more akin to:

```yaml
status:
  conditions:
  - lastTransitionTime: "2025-03-18T10:30:45Z"
    message: Unable to construct a valid DAG from input
    reason: FaultyGraph
    status: "False"
    type: Ready
  - lastTransitionTime: "2025-03-18T10:30:45Z"
    message: 'failed to validate resource CEL expressions: failed to dry-run expression
      schema.spec.regions[2]: failed to evaluate expression: index out of bounds:
      2'
    reason: InvalidCEL
    status: "False"
    type: GraphVerified
  - lastTransitionTime: "2025-03-18T10:30:45Z"
    message: Reconciler cannot be started due to faulty graph
    reason: FaultyGraph
    status: False
    type: ReconcilerReady
  - lastTransitionTime: "2025-03-18T10:30:45Z"
    message: Custom Resource Definition cannot be synced due to faulty graph
    reason: FaultyGraph
    status: False
    type: CustomResourceDefinitionSynced
```

Most importantly:

> Condition types should be named in PascalCase. Short condition names are preferred (e.g. "Ready" over "MyResourceReady").

> Message is intended to be a human-readable phrase or sentence, which may contain specific details of the individual occurrence.

> Condition type names should describe the current observed state of the resource, rather than describing the current state transitions. This typically means that the name should be an adjective ("Ready", "OutOfDisk") or a past-tense verb ("Succeeded", "Failed") rather than a present-tense verb ("Deploying"). Intermediate states may be indicated by setting the status of the condition to Unknown.

- Either follow [kstatus convention](https://pkg.go.dev/sigs.k8s.io/cli-utils/pkg/kstatus#section-readme) (a bit outdated wrt new Kubernetes conventions) of using a set of abnormal-true conditions, OR have a top-level `type=Ready` condition that summarizes the status.

You can then use `status.conditions[?(@.type=="Ready")].reason` as the state to show in the printer columns.

**Reproduction Steps**:

Apply the following RGD:

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: example
spec:
  schema:
    apiVersion: v1alpha1
    kind: Example
    spec:
      berries: '[]string | required'
  resources:
    - id: cm
      includeWhen:
        - ${schema.spec.berries.size() >= 3}
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: '${schema.metadata.name}-${schema.spec.berries[2]}-cm'
```

Then look at its state in the cluster.

**Versions**:
- kro version: 0.2.2
- Kubernetes Version (`kubectl version`): v1.27.1

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Which option describes the most your issue?

ResourceGraphDefinition (Create, Update, Deletion)
