### ISSUE TITLE
Nil pointer dereference during CEL evaluation when ResourceGraphDefinition includes CRD and CEL-using resources

### ISSUE THREAD

**Issue by Rakhmanov** [kro-run/kro#461]
### Description

**Observed Behavior:**

When a ResourceGraphDefinition contains:

- a CRD resource without CEL expressions, and
- other resources that do use CEL expressions

KRO attempts to evaluate CEL expressions across all resources. This leads to a Go panic when accessing resource.emulatedObject on the CRD, which doesn’t support it.

Manifesting as:
`panic: runtime error: invalid memory address or nil pointer dereference`

**Expected Behavior:**

Resources without CEL expressions should be safely excluded from CEL validation logic.

**Reproduction Steps** (Please include `ResourceGraphDefinition` and `Instances` files):

Apply the following ResourceGraphDefinition:

```
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: example-graph
spec:
  schema:
    group: example.group
    apiVersion: v1
    kind: ExampleKind
    spec:
      name: string

  resources:
    - id: myCrd
      template:
        apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        metadata:
          name: examples.example.group
        spec:
          group: example.group
          names:
            plural: examples
            singular: example
            kind: Example
            listKind: ExampleList
          scope: Namespaced
          versions:
            - name: v1
              schema:
                openAPIV3Schema:
                  type: object
                  properties:
                    metadata:
                      type: object
                    spec:
                      type: object
                    status:
                      type: object
                      properties:
                        ready:
                          type: boolean
                        output:
                          type: object
                          properties:
                            state:
                              type: string
                              enum: ["InProgress", "Failed", "Successful"]
                            message:
                              type: string
              served: true
              storage: true
              subresources:
                status: {}
    - id: role
      template:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: Role
        metadata:
          name: role
        rules:
          - apiGroups: ["example.example.group"]
            resources: ["mycrd", "mycrd/status"]
            verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    - id: roleBinding
      template:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: role-binding
        subjects:
          - kind: ServiceAccount
            name: default
            namespace: default
        roleRef:
          kind: Role
          name: ${role.metadata.name}
          apiGroup: rbac.authorization.k8s.io
```

**Versions**:
- kro version: master
- Kubernetes Version (`kubectl version`): Any

**Involved Controllers**:
- Controller URLs and Versions (if applicable):
https://github.com/kro-run/kro/blob/4a5b2a310b77fbd43f1babfaac53116d309e8980/pkg/graph/builder.go#L635

**Error Logs** (if applicable)**:
```
2025-03-27T16:44:17.515-0400    LEVEL(-5)       Reconciling     {"controller": "resourcegraphdefinition", "controllerGroup": "kro.run", "controllerKind": "ResourceGraphDefinition", "ResourceGraphDefinition": {"name":"example-graph"}, "namespace": "", "name": "example-graph", "reconcileID": "7b00f65b-8e0c-440f-a502-fef4fe9c55be"}
2025-03-27T16:44:17.515-0400    DEBUG   controller.resourceGraphDefinition      Setting resource graph definition as managed{"resourcegraphdefinition": {"name":"example-graph"}}
2025-03-27T16:44:17.515-0400    DEBUG   controller.resourceGraphDefinition      setting resourcegraphdefinition as managed {"resourcegraphdefinition": {"name":"example-graph"}}
2025-03-27T16:44:17.515-0400    DEBUG   controller.resourceGraphDefinition      Syncing resourcegraphdefinition {"resourcegraphdefinition": {"name":"example-graph"}}
2025-03-27T16:44:17.515-0400    DEBUG   controller.resourceGraphDefinition      reconciling resource graph definition graph{"resourcegraphdefinition": {"name":"example-graph"}}
2025-03-27T16:44:17.599-0400    ERROR   Observed a panic        {"controller": "resourcegraphdefinition", "controllerGroup": "kro.run", "controllerKind": "ResourceGraphDefinition", "ResourceGraphDefinition": {"name":"example-graph"}, "namespace": "", "name": "example-graph", "reconcileID": "7b00f65b-8e0c-440f-a502-fef4fe9c55be", "panic": "runtime error: invalid memory address or nil pointer dereference", "panicGoValue": "\"invalid memory address or nil pointer dereference\"", "stacktrace": "goroutine 164 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x30bb778, 0xc000700b70}, {0x2b14340, 0x419b560})\n\t/home/raxx/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/runtime/runtime.go:107 +0x116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\t/home/raxx/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:105 +0x1fa\npanic({0x2b14340?, 0x419b560?})\n\t/home/raxx/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.0.linux-amd64/src/runtime/panic.go:787 +0x136\ngithub.com/kro-run/kro/pkg/graph.dryRunExpression(0xc00029aa00, {0xc000bb2e8a, 0x12}, 0xc000769fa8)\n\t/home/raxx/kro/pkg/graph/builder.go:636 +0x4fe\ngithub.com/kro-run/kro/pkg/graph.validateResourceCELExpressions(0xc0008bd6e0, 0xc00098b5f0)\n\t/home/raxx/kro/pkg/graph/builder.go:726 +0x2151\ngithub.com/kro-run/kro/pkg/graph.(*Builder).NewResourceGraphDefinition(0xc00063f4d0, 0xc0000361a0)\n\t/home/raxx/kro/pkg/graph/builder.go:214 +0xd67\ngithub.com/kro-run/kro/pkg/controller/resourcegraphdefinition.(*ResourceGraphDefinitionReconciler).reconcileResourceGraphDefinitionGraph(0xc00062fb80, {0x30bb778, 0xc000700e10}, 0xc0000361a0)\n\t/home/raxx/kro/pkg/controller/resourcegraphdefinition/controller_reconcile.go:107 +0x96\ngithub.com/kro-run/kro/pkg/controller/resourcegraphdefinition.(*ResourceGraphDefinitionReconciler).reconcileResourceGraphDefinition(0xc00062fb80, {0x30bb778, 0xc000700e10}, 0xc0000361a0)\n\t/home/raxx/kro/pkg/controller/resourcegraphdefinition/controller_reconcile.go:41 +0x1cd\ngithub.com/kro-run/kro/pkg/controller/resourcegraphdefinition.(*ResourceGraphDefinitionReconciler).Reconcile(0xc00062fb80, {0x30bb778, 0xc000700e10}, 0xc0000361a0)\n\t/home/raxx/kro/pkg/controller/resourcegraphdefinition/controller.go:112 +0x3ef\nsigs.k8s.io/controller-runtime/pkg/reconcile.(*objectReconcilerAdapter[...]).Reconcile(0x30974c0, {0x30bb778, 0xc000700b70}, {{{0x0, 0x0}, {0xc000788120, 0xd}}})\n\t/home/raxx/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/reconcile/reconcile.go:154 +0x268\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0x30d45e0, {0x30bb778, 0xc000700b70}, {{{0x0, 0x0}, {0xc000788120, 0xd}}})\n\t/home/raxx/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:116 +0x203\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x30d45e0, {0x30bb778, 0xc000700b70}, {{{0x0, 0x0}, {0xc000788120, 0xd}}})\n\t/home/raxx/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:303 +0x438\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x30d45e0, {0x30bb7b0, 0xc0003f5a40})\n\t/home/raxx/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263 +0x4e6\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()\n\t/home/raxx/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224 +0xf4\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 78\n\t/home/raxx/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:220 +0x9ba\n"}
runtime.sigpanic
        /home/raxx/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.0.linux-amd64/src/runtime/signal_unix.go:925
github.com/kro-run/kro/pkg/graph.dryRunExpression
        /home/raxx/kro/pkg/graph/builder.go:636
github.com/kro-run/kro/pkg/graph.validateResourceCELExpressions
        /home/raxx/kro/pkg/graph/builder.go:726
github.com/kro-run/kro/pkg/graph.(*Builder).NewResourceGraphDefinition
        /home/raxx/kro/pkg/graph/builder.go:214
github.com/kro-run/kro/pkg/controller/resourcegraphdefinition.(*ResourceGraphDefinitionReconciler).reconcileResourceGraphDefinitionGraph
        /home/raxx/kro/pkg/controller/resourcegraphdefinition/controller_reconcile.go:107
github.com/kro-run/kro/pkg/controller/resourcegraphdefinition.(*ResourceGraphDefinitionReconciler).reconcileResourceGraphDefinition
        /home/raxx/kro/pkg/controller/resourcegraphdefinition/controller_reconcile.go:41
github.com/kro-run/kro/pkg/controller/resourcegraphdefinition.(*ResourceGraphDefinitionReconciler).Reconcile
        /home/raxx/kro/pkg/controller/resourcegraphdefinition/controller.go:112
sigs.k8s.io/controller-runtime/pkg/reconcile.(*objectReconcilerAdapter[...]).Reconcile
        /home/raxx/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/reconcile/reconcile.go:154
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile
        /home/raxx/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:116
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
        /home/raxx/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:303
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
        /home/raxx/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
        /home/raxx/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224
2025-03-27T16:44:17.599-0400    ERROR   Reconciler error        {"controller": "resourcegraphdefinition", "controllerGroup": "kro.run", "controllerKind": "ResourceGraphDefinition", "ResourceGraphDefinition": {"name":"example-graph"}, "namespace": "", "name": "example-graph", "reconcileID": "7b00f65b-8e0c-440f-a502-fef4fe9c55be", "error": "panic: runtime error: invalid memory address or nil pointer dereference [recovered]"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
        /home/raxx/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
        /home/raxx/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
        /home/raxx/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Which option describes the most your issue?

Common Expression Language (CEL)
