### ISSUE TITLE
Allow ResourceGraphDefinition authors maintain serveral versions

### ISSUE THREAD

**Issue by acll19** [kro-run/kro#482]
### Feature Description

**Problem Statement**:

Users of kro are not likely to start with an stable version of their Resource Graph Definitions (RGD) which means that they could update their RGD spec several times and the way they have to inform their users that a change has been made (and what kind of change even) is by releasing a new version of the resource group.

Currently this is not possible with kro because the `apiVersion` of an RGD is immutable.

**Proposed Solution**:

As I see it, two things need to be considered 1) managing RGD versions in the controller and 2) user experience (UX), as in how to offer an API that's simple to use yet simple to maintain.

Let's start with the second one as I believe the UX will influence the implementation the most.  Given the many ways users could define and evolve their APIs, there is no simple way to solve this problem unless some conventions are in place:
      
- `spec.schema.apiVersion` will always be the latest version of the underlying CRD
- Users can keep old versions under `spec.previousSchemas[*]`
- A previous schema  MUST declare `apiVersion` which MUST be older than `spec.schema.apiVersion`
- A previous schema's `spec` will ONLY declare fields that have been deprecated, the field name has changed or even the field's structure have changed. An example of a field whose structure has changed could be in a previous schema `spec.image` and in the next schema: `spec.image.repository` and `spec.image.tag`. Converting from one to another would not be too hard (this one could be stretch).
- The same goes for a previous schema's status
- Version priority is the same as described [here](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#version-priority) for CRDs

This way, for people interacting with kro for the first time will not need to deal with boilerplate code which will only be needed later if ever. At the same time it is still a simple way for RGD authors who do need to maintain several versions.

Here's an example

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: web-application
spec:
  schema:
    apiVersion: v1beta1
    kind: WebApplication
    spec:
      name: string | required=true description="My Name"
      replicas: integer | default=1 minimum=1 maximum=100
      image: # new way of setting image details
        repository: string | required=true description="Path to the image repository"
        tag: string | required=true description="Image tag"

      ingress:
        enabled: boolean | default=false
        host: string | default="example.com"
        path: string | default="/"

      ports: "[]integer"

      env: "map[string]string"

    status:
      availableReplicas: ${deployment.status.availableReplicas}
      serviceEndpoint: ${service.status.loadBalancer.ingress[0].hostname}

   storage: true # optional, defaults to true when not present
   # note that served here is not present as it would always be true
  
  previousSchemas:
    - apiVersion: v1alpha1 # old version
      # keep only the fields that are no longer part of the immediately above version of this one
      spec:
        image: string | required=true

        tlsCertificate:
          enabled: boolean | default=true
      
      status:
        tlsCertificate: ${certificate.status.conditions[0].status}

    served: true # mandatory, defaults to false
    storage: false #optional

```

On top of that, a  `spec.conversion` object could be defined as follows

```yaml
conversion:
      basic:
        - from: v1beta1
          to: v1alpha1
          rules:
          - field: .spec.image
            destination: spec.image
            transform: "{spec.image.repository}:{spec.image.tag}"
          remove:
            - spec.tlsCertificate
        - from: v1alpha1
          to: v1beta1
          rules:
          - field: .spec.image
            destination: .spec.image
            transform: "repository,tag=Split(.spec.image, ':')"
          preserve:
          - .spec.tlsCertificate
          
      webhook:
      #   ...
``` 

I am not proficient in CEL and I wonder if it can be used for transformations 🤔 

Additionally for more complex cases, a [conversion](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#configure-customresourcedefinition-to-use-conversion-webhooks) object could be added to the `spec.conversion` (see webhook in the example) . Although this brings more flexibility, the fact that the underlying CRDs are managed by kro, after upgrading kro to a new version, user's conversion webhooks may break. This could potentially be a burden for both maintainers and contributors who would probably need to include changes in underlying CRDs in the release notes and users who would be forced to update their conversion webhooks.

Regarding implementation, the XRD type should be extended as well as the `schema.spec.apiVersion` should be unlocked. Additionally a  conversion webhook should be implemented to handle basic conversion  declared in a `spec.conversion`.
I will leave out the details of how to handle `served` and `storage` schemas as I haven't quite figured out how to do it. So if anyone has an idea, feel free to share.

**Alternatives Considered**:

I considered changing `spec.schema` to a list where users can declare all of the supported versions. I thought this would make schemas harder to read specially to understand what has changed from one schema to another.

Another option would be just exposing the CRDs conversion API and just delegating to exiting CRD mechanics in K8s but besides what I mentioned above about this, having only this option would force users to implement/maintain a conversion webhook even for simple cases.

Finally, I also considered the idea of just advising users to create a new RGD whenever they have to make changes. However, although this is a valid approach, it could play against kro adoption as the inability to maintain multiple versions of a resource is something that the target user group of kro could not see with good eyes.

**Additional Context**:

[This Slack thread](https://kubernetes.slack.com/archives/C081TMY9D6Y/p1743059988664869) and this [GitHub Issue](https://github.com/kro-run/kro/issues/428)

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue
* If you are interested in working on this feature, please leave a comment
