### ISSUE TITLE
Introduce CEL function for generating random string

### ISSUE THREAD

**Issue by joshuabaird** [kro-run/kro#499]
### Feature Description

**Problem Statement**:
It would be useful to be able to inject a random string into a _ResourceGraphDefinition_'s `resources` to enforce unique naming for resources -- eg, IAM roles.  This is useful for users who want to provision multiple account-scoped resources (AWS IAM roles) to the same account because these resource names need to be unique.

**Proposed Solution**:
A CEL function that can generate a random string and be used similar to this:

```
resources:
- id: iamRoleResource
   template:
     apiVersion: iam.services.k8s.aws/v1alpha1
     kind: Role
     metadata:
       name: ${schema.spec.name}-cert-${randomString}
```
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue
* If you are interested in working on this feature, please leave a comment
