### ISSUE TITLE
[bug] kro does not detect deleted resources

### ISSUE THREAD

**Issue by denzhel** [kro-run/kro#520]
### Description

**Observed Behavior**:
Deleted resources out of a kro instances are not detected and recreated. Instead, they remain deleted and no log or info is shown when trying to `k describe` 

**Expected Behavior**:

**Reproduction Steps**:
1. Create a kro instance using the following code:
```
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: customintegration
spec:
  schema:
    apiVersion: v1alpha1
    kind: CustomIntegration
    spec:
      name: string
      sns:
      ...
    status:
  resources:
    # sns resources
    - id: iamPolicy
      includeWhen:
        - ${schema.spec.sns.enabled}
      template:
        apiVersion: iam.services.k8s.aws/v1alpha1
        kind: Policy
        metadata:
          name: ${schema.spec.name}-snsfeedback
        spec:
          name: ${schema.spec.name}
          policyDocument: |
          ....
    - id: iamRole
      includeWhen:
        - ${schema.spec.sns.enabled}
      template:
        apiVersion: iam.services.k8s.aws/v1alpha1
        kind: Role
        metadata:
          name: ${schema.spec.name}-snsfeedback
        spec:
          assumeRolePolicyDocument: |
          ....
          policies:
          - ${iamPolicy.status.ackResourceMetadata.arn}
    - id: topic
      includeWhen:
        - ${schema.spec.sns.enabled}
      template:
        apiVersion: sns.services.k8s.aws/v1alpha1
        kind: Topic
        metadata:
          name: ${schema.spec.sns.name}
        spec:
          name: ${schema.spec.sns.name}
          deliveryPolicy: ${schema.spec.sns.deliveryPolicy}
          ....
```
2. Manually delete the topic using `k delete topic <topicName>`
3. Watch the logs of `sns-controller` and `kro`
4. Nothing happens

**Versions**:
- kro version: 0.2.3
- Kubernetes Version (`kubectl version`): 1.31

**Involved Controllers**:
- Controller URLs and Versions (if applicable): happens with all controllers
