### ISSUE TITLE
Wrong API Endpoint used by Kro on Fleet Gitrepos

### ISSUE THREAD

**Issue by samuelgautier** [kro-run/kro#524]
### Description

Hello, 
we are currently experimenting with KRO and exploring different integration scenarios with our GitOps tools including Fleet in order to get data from Azure Service Operator and then ask Fleet to deploy a Helm install of Nginx with parameters coming from Azure.
Here, I'm trying to create a Fleet "GitRepo" from my RGD, but Kro seems to use a wrong API endpoint.
I guess there's something wrong with the API endpoint used but i don't know if this error is from Kro or Fleet CRD.
The plural Kind in Fleet is : gitrepos

**Observed Behavior**:

Here is a trace of the API call performed by Kro with a 404 response code, and you can have a look at the Endpoint used by Kro : 

{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"58c4c9c2-2d9d-4254-949e-29741b735c63","stage":"ResponseComplete","requestURI":"**/apis/fleet.cattle.io/v1alpha1/namespaces/fleet-local/gitrepoes**","verb":"create","user":{"username":"system:serviceaccount:kro:kro","uid":"8a7453ab-9cbe-4664-b941-e72881d39ba2","groups":["system:serviceaccounts","system:serviceaccounts:kro","system:authenticated"],"extra":{"authentication.kubernetes.io/credential-id":["JTI=fb334086-b89c-44c3-b3de-0f06736bf208"],"authentication.kubernetes.io/node-name":["aks-pzkblazsg0g1-13189174-vmss0000rv"],"authentication.kubernetes.io/node-uid":["a4ce941a-890f-4ae5-9295-852cf9f4698d"],"authentication.kubernetes.io/pod-name":["kro-5b5d56bb9-kqn97"],"authentication.kubernetes.io/pod-uid":["a0e3a9aa-a4b6-4cb8-9e3a-53321131404e"]}},"sourceIPs":["10.241.0.50"],"userAgent":"kro/v0.2.3","objectRef":{"resource":"gitrepoes","namespace":"fleet-local","apiGroup":"fleet.cattle.io","apiVersion":"v1alpha1"},"responseStatus":{"metadata":{},"code":**404**},"requestReceivedTimestamp":"2025-04-18T12:27:27.438782Z","stageTimestamp":"2025-04-18T12:27:27.439176Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"kro-cluster-role-binding\" of ClusterRole \"kro-cluster-role\" to ServiceAccount \"kro/kro\""}}

And here is the description of my failed instance : 

The instance : 

```
Name:         ingress-laz-dev97
Namespace:    laz-dev97
Labels:       kro.run/kro-version=v0.2.3
              kro.run/owned=true
              kro.run/resource-graph-definition-id=ba7b93ec-7971-43aa-8454-95a5ec01db40
              kro.run/resource-graph-definition-name=my-ingress-nginx
Annotations:  <none>
API Version:  kro.run/v1alpha1
Kind:         MyIngressNginx
Metadata:
  Creation Timestamp:  2025-04-18T12:27:08Z
  Finalizers:
    kro.run/finalizer
  Generation:        1
  Resource Version:  107333679
  UID:               8fa13279-d692-4519-8e43-70516af4b437
Spec:
  Ingress Controller Custom Options:
    custom_subnet:   sub-dosn-np-02-aks-clu02
    custom_vnet:     vn-dosn-np-aks
    custom_vnet_rg:  rg-vn-dosn-np-aks
  Ingress Controller Helm Values:
    controller.service.loadBalancerIP:  10.131.180.86
  Name:                                 ingress-laz-dev97
  Namespace:                            laz-dev97
Status:
  Conditions:
    Last Transition Time:  2025-04-18T12:27:27Z
    Message:               **failed to create resource: the server could not find the requested resource**
    Observed Generation:   1
    Reason:                ReconciliationFailed
    Status:                False
    Type:                  InstanceSynced
  State:                   ERROR
Events:                    <none>  
```

**Expected Behavior**:

I think that the API should use "gitrepos" instead of "gitrepoes"
When I try to create manually (kubectl apply -f ) the GitRepo object, it works.

**Reproduction Steps** (Please include `ResourceGraphDefinition` and `Instances` files):

Here is my RGD (still in draft) : 

```
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: my-ingress-nginx
spec:
  schema:
    apiVersion: v1alpha1
    kind: MyIngressNginx
    spec:
      # Spec fields that users can provide.
      name: string
      namespace: string | default=default
      IngressControllerCustomOptions:
        custom_subnet: string | default=""
        custom_vnet: string | default=""
        custom_vnet_rg: string | default=""
      IngressControllerHelmValues: "map[string]string"
    status:
      

  resources:
    - id: azureResourceGroup
      template:
        apiVersion: resources.azure.com/v1api20200601
        kind: ResourceGroup
        metadata:
          name: ${schema.spec.IngressControllerCustomOptions.custom_vnet_rg}
          namespace: ${schema.spec.namespace}
          annotations:
            serviceoperator.azure.com/reconcile-policy: skip
        spec:
          azureName: ${schema.spec.IngressControllerCustomOptions.custom_vnet_rg}
          location: francecentral

    - id: azureVnet
      template:
        apiVersion: network.azure.com/v1api20240301
        kind: VirtualNetwork
        metadata:
          name: ${schema.spec.IngressControllerCustomOptions.custom_vnet}
          namespace: ${schema.spec.namespace}
          annotations:
            serviceoperator.azure.com/reconcile-policy: skip
        spec:
          azureName: ${schema.spec.IngressControllerCustomOptions.custom_vnet}
          owner:
            name: ${schema.spec.IngressControllerCustomOptions.custom_vnet_rg}

    - id: azureSubnet
      template:
        apiVersion: network.azure.com/v1api20240301
        kind: VirtualNetworksSubnet
        metadata:
          name: ${schema.spec.IngressControllerCustomOptions.custom_subnet}
          namespace: ${schema.spec.namespace}
          annotations:
            serviceoperator.azure.com/reconcile-policy: skip
        spec:
          azureName: ${schema.spec.IngressControllerCustomOptions.custom_subnet}
          owner: 
            name: ${schema.spec.IngressControllerCustomOptions.custom_vnet}
    - id: cmValues
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: ${schema.spec.name}-ingress-nginx-values
          namespace: ${schema.spec.namespace}
        data:
          values.yaml: |-
            namespacePrefix: ${schema.spec.namespace}
            namespace: ${schema.spec.namespace}
            custom_subnet: ${schema.spec.IngressControllerCustomOptions.custom_subnet}
            subnet_range: ${azureSubnet.status.addressPrefix}
            loadBalancerIP: ${schema.spec.IngressControllerHelmValues.filter(key, key == "controller.service.loadBalancerIP").map(item, schema.spec.IngressControllerHelmValues[item]).join("\n")}
    - id: gitRepoSecret
      template:
        apiVersion: v1
        data:
          password: XXXXXXXXXXXXXXXXXXXXXXXXXX
          username: XXXXXXXXXXXXXXXXXXXXXXXXXX
        kind: Secret
        type: kubernetes.io/basic-auth
        metadata:
          name: auth-gitrepo-psgr03231
          namespace: fleet-local
    - id: gitRepoLocal
      template:
        kind: GitRepo
        apiVersion: fleet.cattle.io/v1alpha1
        metadata:
          name: psgr03231-manifests
          namespace: fleet-local
        spec:
          branch: main
          repo: https://gitlab-repo-gpf.apps.eul.sncf.fr/dosn/cloud/04228/conteneurisation/psgr03231.git
          clientSecretName: auth-gitrepo-psgr03231
          paths:
          - /fleet/ingress-nginx


```

Instance file :

```
apiVersion: kro.run/v1alpha1
kind: MyIngressNginx
metadata:
  name: ingress-laz-dev97
  namespace: laz-dev97
spec:
  name: ingress-laz-dev97
  namespace: laz-dev97
  IngressControllerCustomOptions:
    custom_vnet: "vn-dosn-np-aks"
    custom_subnet: "sub-dosn-np-02-aks-clu02"
    custom_vnet_rg: "rg-vn-dosn-np-aks"
  IngressControllerHelmValues:
    controller.service.loadBalancerIP: "10.131.180.86"
```
  

**Versions**:
- kro version: 0.2.3
- Kubernetes Version (`kubectl version`): 1.31.5

**Involved Controllers**:
- Controller URLs and Versions (if applicable): 
- Azure Service Operator 2.12
- Fleet 0.12.1

**Error Logs** (if applicable)**:
```
Paste any relevant logs here
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
