### ISSUE TITLE
Kro does not update resources when updates are made to externalRefs

### ISSUE THREAD

**Issue by benfogel** [kro-run/kro#552]
### Description

**Observed Behavior**: This is an observation on the recent external references feature adding in #273. Similar to #519, Kro does not update resources created via a `ResourceGraphDefinition` when externalRef values are updated. There are also no updates when hitting the resync period, as kro detects the same generation value in the `ResourceGraphDefinition` instance. 

**Expected Behavior**:
If the externalRef value changes, then Kro should update `ResourceGraphDefinition` resources.
Alternatively, the resync period should also update the `ResourceGraphDefinition` with the latest values presented via externalRef.

**Reproduction Steps** (Please include `ResourceGraphDefinition` and `Instances` files):
```
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: externalreferencetest
spec:
  schema:
    apiVersion: v1alpha1
    kind: ExternalReferenceTest
    spec:
      name: string
  resources:
    - id: config
      externalRef:
        name: configuration-values
        namespace: default
        apiVersion: custom.io/v1alpha1
        kind: Config
    - id: configmap
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: demo
        data:
          reference: ${config.spec.someDynamicVariable}

---

apiVersion: kro.run/v1alpha1
kind: ExternalReferenceTest
metadata:
  name: test
  namespace: default
spec:
  name: test

---

apiVersion: custom.io/v1alpha1
kind: Config
metadata:
  name: configuration-values
  namespace: default
spec:
  someDynamicVariable: foo
```

If someDynamicVariable is changed from `foo` to `bar`, the generated configmap remains unchanged. 

**Versions**:
- kro version: main

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
