### ISSUE TITLE
Not able to use the externalRef in the resource graph defnition

### ISSUE THREAD

**Issue by Ashish7812** [kro-run/kro#565]
<h3>Observation</h3>
I installed the latest version of kro i.e 0.3.0. 

```text
$ helm list -n kro
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kro     kro             1               2025-05-23 13:34:51.9961904 +0530 IST   deployed        kro-0.3.0       0.3.0

```

I tried out the externalRef in the following resource graph definition.

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: catalog-storage-v1
spec:
  schema:
    apiVersion: v1alpha1
    kind: CatalogStorage
    spec:
      name: string
    status:
      bucketLocation: '${s3.status.location}'
  resources:
    - id: input
      externalRef:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: bucket-config
          namespace: default
    - id: s3
      template:
        apiVersion: s3.services.k8s.aws/v1alpha1
        kind: Bucket
        metadata:
          name: '${input.data.bucketName}'
        spec:
          name: '${input.data.bucketName}'

```

When I am trying to create the resource graph definition I am getting the following error.

```text
$ kubectl create -f exref.yaml
Error from server (BadRequest): error when creating "exref.yaml": ResourceGraphDefinition in version "v1alpha1" cannot be handled as a ResourceGraphDefinition: strict decoding error: unknown field "spec.resources[0].externalRef"
```
