### ISSUE TITLE
Unable to refer an external configmap in the resource graph definition

### ISSUE THREAD

**Issue by Ashish7812** [kro-run/kro#568]
@barney-s  I tried to refer a configmap as an external resource but cannot. Have you tried to refer an external configmap in any of the resources?

I tried the following example with the new 0.3.0 version of KRO.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo
data:
  bucketName: <a unique bucket name>
```
The above one is created outside the KRO.

Now in one of the resource graph definition I am trying to refer the data <b>bucketName</b>. ex: in the environment variable section of the deployment. The resource graph definition is depicted below. 

```yaml

apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: catalog
spec:
  schema:
    apiVersion: v1alpha1
    kind: Catalog
    spec:
      name: string
      image: string | default="nginx"

  resources:
    - id: input
      externalRef:
       apiVersion: v1
       kind: ConfigMap
       metadata:
         name: demo
         namespace: default

    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.spec.name} # Use the name provided by user
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: ${schema.spec.name}
          template:
            metadata:
              labels:
                app: ${schema.spec.name}
            spec:
              containers:
                - name: ${schema.spec.name}
                  image: ${schema.spec.image} # Use the image provided by user
                  env:
                    - name: BUCKET_NAME
                      value: ${input.data.bucketName}
                  ports:
                    - containerPort: 80
```

The reference is 

```text
  - name: BUCKET_NAME
    value: ${input.data.bucketName}
```

but when I am trying to create the resource graph definition it fails to create stating can not evaluate the expression ${input.data.bucketName} no such key bucketName.

**Comment by barney-s** [comment]
Duplicate of #535

**Comment by a-hilaly** [comment]
Thank you @Ashish7812 for opening this issue, we are currently tracking this one in https://github.com/kro-run/kro/issues/535 - the solution would be enable optional [CEL variables](https://github.com/google/cel-go/blob/746d711377ddc7e49686f6cce1346b4ed6659d11/cel/library.go#L207-L362)

**Comment by Ashish7812** [comment]
@a-hilaly after the optional CEL variables are enabled Can I refer the configmap data field in the resource graph definition? This is an important usecase for us. We want to consume the configmap in the resourcegraph definition.

**Comment by jakobmoellerdev** [comment]
Hey folks, just to mention that this problem here does not need to use CEL Optionals:

simply reference your config map as such

```
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: catalog
spec:
  schema:
    apiVersion: v1alpha1
    kind: Catalog
    spec:
      name: string
      image: string | default="nginx"

  resources:
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.spec.name} # Use the name provided by user
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: ${schema.spec.name}
          template:
            metadata:
              labels:
                app: ${schema.spec.name}
            spec:
              containers:
                - name: ${schema.spec.name}
                  image: ${schema.spec.image} # Use the image provided by user
                  env:
                    - name: BUCKET_NAME
                      valueFrom:
                        configMapKeyRef:
                          name: demo
                          key: bucketName
                  ports:
                    - containerPort: 80
```

that being said. I can still write up an example that does this via optionals
