### ISSUE TITLE
failed to extract CEL expressions from StorageClass

### ISSUE THREAD

**Issue by viswanathanb** [kro-run/kro#585]
I am trying to use Kro to create a RG to use a value generated in CephBlockPoolRadosNamespace in StorageClass. 
 
ResourceGraph

```
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
    name: ceph-rbd-rg
spec:
  schema:
    apiVersion: v1
    kind: StorageApp
    spec:
      name: ceph-rbd
    status:
      clusterID: ${mainPool.status.info.clusterID}
  resources:
    - id: mainPool
      template:
        kind: CephBlockPoolRadosNamespace
        apiVersion: ceph.rook.io/v1
        spec:
          blockPoolName: default
        metadata:
          name: r-west-04
          namespace: rook-ceph

    - id: mainStorageClass
      template:
        kind: StorageClass
        apiVersion: storage.k8s.io/v1
        metadata:
          name: ceph-rbd-r-west-04
        spec:
          provisioner: rook-ceph.rbd.csi.ceph.com
          parameters:
            clusterID: ${mainPool.status.info.clusterID}
            pool: default
            imageFormat: "2"
            imageFeatures: layering

            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph

            csi.storage.k8s.io/fstype: ext4
          mountOptions:
          - discard
          reclaimPolicy: Retain
          allowVolumeExpansion: true
```

Error

", "error": "failed to build resource \"mainStorageClass\": failed to extract CEL expressions from schema for resource mainStorageClass: error getting field schema for path .spec: schema not found for field spec"}
