### ISSUE TITLE
Mega Feature: Add support for external references

### ISSUE THREAD

**Issue by candonov** [kro-run/kro#72]
Add ability to reference fields from external to the ResourceGroups resources that exist in the cluster.

For example, reference `data` from an existing ConfigMap: 

Sample ConfigMap:
```bash
❯ k get configmap this -o yaml
apiVersion: v1
kind: ConfigMap
data:
  awsAccountID: "111122223333"
  clusterName: test-cluster
  eksOIDC: oidc.eks.us-east-1.amazonaws.com/id/EXAMPLE0123456789
  region: us-east-1
  subnetIDs: subnet-1111aaaa2222bbbbb,subnet-1111aaaa2222bbbbb,subnet-1111aaaa2222bbbbb
  vpcID: <vpc-1111aaaa2222bbbbb>
```
Option 1: Import an external resource explicitly without taking over control of it and reference values from other resources. Import by one of three options 1/ `name`, 2/ `labels`, 3/ `annotations`
```yaml
spec:
  schema:
    apiVersion: v1alpha1
    kind: s3podidentity
    spec:
...
  resources: 
  - name: externalConfigmap
    externalRef: 
      apiVersion: v1
      kind: ConfigMap
      metadata:
          namespace: default
          name: my-config-map-name
          labels:
             prod: my-prod-label
          annotations:
             prod: my-prod-annotation
....
  - name: anyResource
    var: ${externalConfigmap.data.region}
```    

Option 2: just reference it inline.
```yaml
...
spec:
  schema:
    apiVersion: v1alpha1
    kind: s3podidentity
    spec:
      name: string
      namespace: string | default="default"
      region: string | default=${externalref.configmap.default.this.data.region}
      clusterName: string | default=${externalref.configmap(default, name).data.clusterName}
```
Option 1 contains more lines of yaml but is readable and easier to implement hence it is the preferred option.

**Comment by rahtr** [comment]
Great idea! This approach can also streamline creating roles and policies. Instead of duplicating the same IAM policy or role, we can use a centralized ConfigMap and reference it across kro applications object and only override the values that are distinct.

**Comment by amirahav** [comment]
This would be a very beneficial feature that would greatly improve the usability of kro.
It would allow the referencing of configuration from configmaps, and if ACK implements read only resources, would allow referencing of other AWS resources.

**Comment by kubernetes-stuff** [comment]
Definitely agree - option 2 is my preferred approach if that is feasible.  I can see cases where we would want a cluster owner would want to onboard a tenant and reference a resource created before running through the kro-orchestration tenant onboarding flow

**Comment by khalilj** [comment]
+1

**Comment by newtondev** [comment]
Good suggestion. Definitely need this feature. Just as long as you have the correct permissions (RBAC) to read from the external reference, then it will be quite a secure solution.

**Comment by barney-s** [comment]
Please take a look at #273 which is attempting to implement this is a slightly different way than the suggestions here. Essentially we introduce a `readOnly` flag to resource. This allows a few things which we found useful.

**Comment by a-hilaly** [comment]
I'm trying to explore how we could suport external references in CEL expressions without requiring users to manually define them in the RGD. In theory we could detect them automatically using the existing `${}` expressions. For example:

```yaml
data:
  someKey: "${
      externalRef(ConfigMap, default, name).
        readyWhen().includeWhen().
        data.something
    }"
```

By inspecting the CEL AST, we can identify when an "external" resource is being referenced and automatically register it as a virtual resource in the graph (we could name it read only, external, or something else). What i'm thinking now is that, there are two parts into this technique:
1/ Building the graph & RGD comprehention
    - when parsing the RGD, we can analyze CEL expressions to detect references to other resources
    - These references can be added to the graph as dependencies, eliminating the need for users to define them manually
    - this also allows us to validate CEL expressions ahead of time, ensuring that referenced CRDs exist in the cluster

2/ Validating before DAG execution:
    - before running the DAG, we can check that all referenced resources exist.
    - this prevents runtime errors where an expected resource is missing

**Comment by a-hilaly** [comment]
Has a chat with @barney-s and actually we're thinking that the CEL function approach isn't complete. We still want to support `readyWhen`, maybe `includeWhen`, and also benefit from the dynamic names/namespaces/labels etc....

Another thought, we could extend #273 to also support selecting resources based on labels. example below:

 
```yaml
  resources: 
  - name: exCollection
    template: 
     apiVersion: v1
     kind: ConfigMap
     metadata:
       name: prefix-${schema.spec.name}
       namespace: default 
       # labels:
       #  a: b
```

**Comment by a-hilaly** [comment]
the other thought we're having here is maybe we need a different name than `template` for the readOnly resources. For instance the collections mega feature might have something like a `collection` directive https://github.com/kro-run/kro/issues/17

**Comment by isihu** [comment]
How about using the `vars` layer proposed in [#17](https://github.com/kro-run/kro/issues/17#issuecomment-2489879703)?
```
apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: Application
spec:
  apiVersion: v1alpha1
  kind: Application
  definition:
    spec:
      name: string
  vars:
    - name: image
      function: lookup
      input:
        kind: ConfigMap
        name: environment-configs 
        key: IMAGE
  resources:
    - id: deployment
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.spec.name}
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: deployment
          template:
            metadata:
              labels:
                app: deployment
            spec:
              containers:
                - name: ${schema.spec.name}
                  image: ${vars.image} 
```

It would be similar to [Kyverno's](https://kyverno.io/docs/writing-policies/variables/#inline-variables) `context`.
Very readable and could be used for debugging by logging out current variable values.
