### ISSUE TITLE
RG changes seem to apply but don't propagate to resources 

### ISSUE THREAD

**Issue by candonov** [kro-run/kro#76]
Steps to reproduce:
Create a ResourceGroup with deployment, set imagePullPolicy to IfNotPresent:
```
          spec:
            serviceAccountName: ${spec.name}
            containers:
            - name: ${spec.name}
              image: ${spec.image}
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: ${spec.port}
```
Change the imagePullPolicy to Always and re-apply:
```
          spec:
            serviceAccountName: ${spec.name}
            containers:
            - name: ${spec.name}
              image: ${spec.image}
              imagePullPolicy: Always
              ports:
              - containerPort: ${spec.port}
```
Validate that the RG was updated:
```
❯ k get rg application.x.symphony.k8s.aws -o yaml| grep imagePullPolicy
              imagePullPolicy: Always
```
Create an instance and check the deployment:
```
❯ k get deployments.ap s3demo -o yaml |grep imagePull
        imagePullPolicy: IfNotPresent
```
Add a service account to the resource group:
```
  - name: serviceaccount
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: ${spec.name}
        namespace: ${spec.namespace}
```
Reapply the RG, create another instance, the new instance doesn't create a serviceaccount.
